import type { Metadata } from 'next'
import localfont from 'next/font/local'
import './globals.css'

const inter = localfont({
  src: './fonts/interVF.woff2',
  variable: '--font-inter',
  weight: '400 500 600'
})

const baumans = localfont({
  src: './fonts/BaumansVF.woff2',
  variable: '--font-baumans',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='h-full antialiased dark'>
      <body
        className={` ${inter.variable} ${baumans.variable} flex h-full min-h-full flex-col antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
